import { getCDNPath } from '@/utils/env'

const getImgUrl = (name) => getCDNPath(`/decoration/${name}`)

export const decorationImages = [
  {
    id: 'decoration1',
    name: '装饰器1',
    src: getImgUrl('gif1.gif'),
    css: { 'background-position': 'left bottom' },
  },
  {
    id: 'decoration2',
    name: '装饰器2',
    src: getImgUrl('gif2.gif'),
    css: { 'background-position': 'center' },
  },
  {
    id: 'decoration3',
    name: '装饰器3',
    src: getImgUrl('gif3.gif'),
    css: { 'background-position': 'right top' },
  },
  {
    id: 'decoration4',
    name: '装饰器4',
    src: getImgUrl('gif4.gif'),
    css: { 'background-position': 'right bottom' },
  },
  {
    id: 'decoration5',
    name: '装饰器5',
    src: getImgUrl('gif5.gif'),
    css: { 'background-position': 'left top' },
  },
  {
    id: 'decoration6',
    name: '装饰器6',
    src: getImgUrl('gif6.gif'),
    css: { 'background-position': 'center' },
  },
  {
    id: 'decoration7',
    name: '装饰器7',
    src: getImgUrl('gif7.gif'),
    css: { 'background-size': 'contain', 'background-position': 'left top' },
  },
  {
    id: 'decoration8',
    name: '装饰器8',
    src: getImgUrl('gif8.gif'),
    css: { 'background-size': 'contain', 'background-position': 'left top' },
  },
  {
    id: 'decoration9',
    name: '装饰器9',
    src: getImgUrl('gif9.gif'),
    css: { 'background-size': 'contain', 'background-position': 'left top' },
  },
  {
    id: 'decoration10',
    name: '装饰器10',
    src: getImgUrl('gif10.gif'),
    css: { 'background-size': 'contain', 'background-position': 'left top' },
  },
  {
    id: 'decoration11',
    name: '装饰器11',
    src: getImgUrl('gif11.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration12',
    name: '装饰器12',
    src: getImgUrl('gif12.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration13',
    name: '装饰器13',
    src: getImgUrl('gif13.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration14',
    name: '装饰器14',
    src: getImgUrl('gif14.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration15',
    name: '装饰器15',
    src: getImgUrl('gif15.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration16',
    name: '装饰器16',
    src: getImgUrl('gif16.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration17',
    name: '装饰器17',
    src: getImgUrl('gif17.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration18',
    name: '装饰器18',
    src: getImgUrl('gif18.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration19',
    name: '装饰器19',
    src: getImgUrl('gif19.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration20',
    name: '装饰器20',
    src: getImgUrl('gif20.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration21',
    name: '装饰器21',
    src: getImgUrl('gif21.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration22',
    name: '装饰器22',
    src: getImgUrl('gif22.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration23',
    name: '装饰器23',
    src: getImgUrl('gif23.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration24',
    name: '装饰器24',
    src: getImgUrl('gif24.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration25',
    name: '装饰器25',
    src: getImgUrl('gif25.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration26',
    name: '装饰器26',
    src: getImgUrl('gif26.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration27',
    name: '装饰器27',
    src: getImgUrl('gif27.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration28',
    name: '装饰器28',
    src: getImgUrl('gif28.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration29',
    name: '装饰器29',
    src: getImgUrl('gif29.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration30',
    name: '装饰器30',
    src: getImgUrl('gif30.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration31',
    name: '装饰器31',
    src: getImgUrl('gif31.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration32',
    name: '装饰器32',
    src: getImgUrl('gif32.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration33',
    name: '装饰器33',
    src: getImgUrl('gif33.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration34',
    name: '装饰器34',
    src: getImgUrl('gif34.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration35',
    name: '装饰器35',
    src: getImgUrl('gif35.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration36',
    name: '装饰器36',
    src: getImgUrl('gif36.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration37',
    name: '装饰器37',
    src: getImgUrl('gif37.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration38',
    name: '装饰器38',
    src: getImgUrl('gif38.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration39',
    name: '装饰器39',
    src: getImgUrl('gif39.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration40',
    name: '装饰器40',
    src: getImgUrl('gif40.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration41',
    name: '装饰器41',
    src: getImgUrl('gif41.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration42',
    name: '装饰器42',
    src: getImgUrl('gif42.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration43',
    name: '装饰器43',
    src: getImgUrl('gif43.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration44',
    name: '装饰器44',
    src: getImgUrl('gif44.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration45',
    name: '装饰器45',
    src: getImgUrl('gif45.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration46',
    name: '装饰器46',
    src: getImgUrl('gif46.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration47',
    name: '装饰器47',
    src: getImgUrl('gif47.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration48',
    name: '装饰器48',
    src: getImgUrl('gif48.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration49',
    name: '装饰器49',
    src: getImgUrl('gif49.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
  {
    id: 'decoration50',
    name: '装饰器50',
    src: getImgUrl('gif50.png'),
    css: { 'background-position': 'center', 'background-size': 'contain' },
  },
]

