import { ComType } from '@/config/data-source'

export const decorationConfig = {
  alias: '装饰器',
  icon: 'pushpin',
  type: ComType.com,
  attr: { w: 200, h: 200 },
  config: {
    img: 'gif1.gif',
  },
  apis: {},
  apiData: {},
  events: {},
  actions: {},
}


export const presetImages = [
  { url: 'gif1.gif', css: { 'background-position': 'left bottom' } },
  { url: 'gif2.gif', css: { 'background-position': 'center' } },
  { url: 'gif3.gif', css: { 'background-position': 'right top' } },
  { url: 'gif4.gif', css: { 'background-position': 'right bottom' } },
  { url: 'gif5.gif', css: { 'background-position': 'left top' } },
  { url: 'gif6.gif', css: { 'background-position': 'center' } },
  { url: 'gif7.gif', css: { 'background-size': 'contain', 'background-position': 'left top' } },
  { url: 'gif8.gif', css: { 'background-size': 'contain', 'background-position': 'left top' } },
  { url: 'gif9.gif', css: { 'background-size': 'contain', 'background-position': 'left top' } },
  { url: 'gif10.gif', css: { 'background-size': 'contain', 'background-position': 'left top' } },
  { url: 'gif11.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif12.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif13.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif14.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif15.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif16.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif17.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif18.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif19.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif20.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif21.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif22.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif23.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif24.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif25.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif26.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif27.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif28.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif29.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif30.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif31.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif32.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif33.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif34.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif35.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif36.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif37.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif38.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif39.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif40.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif41.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif42.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif43.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif44.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif45.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif46.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif47.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif48.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif49.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
  { url: 'gif50.png', css: { 'background-position': 'center', 'background-size': 'contain' } },
]
